### PR TITLE
Add the ability to reset modal on close

### PR DESCRIPTION
**Pull request by dacoolman**
Add the ability to reset the modal to step 1 when it is closed instead of saving its position
Add attribute of "reset on close" to the form to enable reseting

### CODE REVIEW

**Comment by ngzhian** [comment]
@dacoolman thanks for the PR!
I would prefer it to be `"true"` rather than `"1"`, what do you think?
Also the comparison should be using `===` instead of `==`, and spaces around the comparison, i.e.

```
a === b // yes
a===b // no
```

**Comment by dacoolman** [comment]
Sure thing, should be updated now

**Comment by ngzhian** [comment]
@dacoolman 2 last nit:
1. use single quotes instead of double quotes for `'true'`
2. `x === 'true' ? true : false` is the same as `x === 'true'`, so we can remove the ternary check
Thanks for your PR! :D

**Comment by dacoolman** [comment]
Oh right, okay should be updated

**Comment by ngzhian** [comment]
Looks great! Thanks :)

**Pull request merged**
